/**
 * Error Keys - Used to identify error types
 * Shared between frontend and backend
 */
export const ERROR_KEYS = {
  AUTH: {
    INVALID_CREDENTIALS: 'AUTH.INVALID_CREDENTIALS',
    TOKEN_REQUIRED: 'AUTH.TOKEN_REQUIRED',
    TOKEN_INVALID: 'AUTH.TOKEN_INVALID',
    REFRESH_TOKEN_REQUIRED: 'AUTH.REFRESH_TOKEN_REQUIRED',
    REFRESH_TOKEN_INVALID: 'AUTH.REFRESH_TOKEN_INVALID',
    AUTHENTICATION_REQUIRED: 'AUTH.AUTHENTICATION_REQUIRED',
    ADMIN_ACCESS_REQUIRED: 'AUTH.ADMIN_ACCESS_REQUIRED',
    TOKEN_REUSE_DETECTED: 'AUTH.TOKEN_REUSE_DETECTED',
  },
  VALIDATION: {
    INVALID_INPUT: 'VALIDATION.INVALID_INPUT',
    REQUIRED_FIELD: 'VALIDATION.REQUIRED_FIELD',
    INVALID_EMAIL: 'VALIDATION.INVALID_EMAIL',
    INVALID_PHONE: 'VALIDATION.INVALID_PHONE',
    PASSWORD_TOO_SHORT: 'VALIDATION.PASSWORD_TOO_SHORT',
    PASSWORD_WEAK: 'VALIDATION.PASSWORD_WEAK',
    IMAGES_NOT_BELONG_TO_PROJECT: 'VALIDATION.IMAGES_NOT_BELONG_TO_PROJECT',
  },
  NOT_FOUND: {
    USER_NOT_FOUND: 'NOT_FOUND.USER_NOT_FOUND',
    PROJECT_NOT_FOUND: 'NOT_FOUND.PROJECT_NOT_FOUND',
    CATEGORY_NOT_FOUND: 'NOT_FOUND.CATEGORY_NOT_FOUND',
    MAIN_IMAGE_NOT_FOUND: 'NOT_FOUND.MAIN_IMAGE_NOT_FOUND',
    PAGE_NOT_FOUND: 'NOT_FOUND.PAGE_NOT_FOUND',
    RESOURCE_NOT_FOUND: 'NOT_FOUND.RESOURCE_NOT_FOUND',
  },
  CONFLICT: {
    EMAIL_ALREADY_EXISTS: 'CONFLICT.EMAIL_ALREADY_EXISTS',
    PROJECT_TITLE_EXISTS: 'CONFLICT.PROJECT_TITLE_EXISTS',
  },
  SERVER: {
    REGISTRATION_FAILED: 'SERVER.REGISTRATION_FAILED',
    LOGIN_FAILED: 'SERVER.LOGIN_FAILED',
    FETCH_USER_FAILED: 'SERVER.FETCH_USER_FAILED',
    REFRESH_TOKEN_FAILED: 'SERVER.REFRESH_TOKEN_FAILED',
    FETCH_PROJECTS_FAILED: 'SERVER.FETCH_PROJECTS_FAILED',
    FETCH_FAVOURITE_PROJECTS_FAILED: 'SERVER.FETCH_FAVOURITE_PROJECTS_FAILED',
    CREATE_PROJECT_FAILED: 'SERVER.CREATE_PROJECT_FAILED',
    UPDATE_PROJECT_FAILED: 'SERVER.UPDATE_PROJECT_FAILED',
    DELETE_PROJECT_FAILED: 'SERVER.DELETE_PROJECT_FAILED',
    SUBMIT_CONTACT_FAILED: 'SERVER.SUBMIT_CONTACT_FAILED',
  },
  NETWORK: {
    CONNECTION_ERROR: 'NETWORK.CONNECTION_ERROR',
    TIMEOUT: 'NETWORK.TIMEOUT',
    SERVER_ERROR: 'NETWORK.SERVER_ERROR',
    UNKNOWN_ERROR: 'NETWORK.UNKNOWN_ERROR',
  },
} as const;

export type ErrorKey = typeof ERROR_KEYS[keyof typeof ERROR_KEYS][keyof typeof ERROR_KEYS[keyof typeof ERROR_KEYS]];
