/**
 * Error Keys - Used to identify error types
 * Shared between frontend and backend
 */
export const ERROR_KEYS = {
  AUTH: {
    INVALID_CREDENTIALS: 'AUTH.INVALID_CREDENTIALS',
    TOKEN_REQUIRED: 'AUTH.TOKEN_REQUIRED',
    TOKEN_INVALID: 'AUTH.TOKEN_INVALID',
    REFRESH_TOKEN_REQUIRED: 'AUTH.REFRESH_TOKEN_REQUIRED',
    REFRESH_TOKEN_INVALID: 'AUTH.REFRESH_TOKEN_INVALID',
    AUTHENTICATION_REQUIRED: 'AUTH.AUTHENTICATION_REQUIRED',
    ADMIN_ACCESS_REQUIRED: 'AUTH.ADMIN_ACCESS_REQUIRED',
    TOKEN_REUSE_DETECTED: 'AUTH.TOKEN_REUSE_DETECTED',
  },
  VALIDATION: {
    INVALID_INPUT: 'VALIDATION.INVALID_INPUT',
    REQUIRED_FIELD: 'VALIDATION.REQUIRED_FIELD',
    INVALID_EMAIL: 'VALIDATION.INVALID_EMAIL',
    INVALID_PHONE: 'VALIDATION.INVALID_PHONE',
    PASSWORD_TOO_SHORT: 'VALIDATION.PASSWORD_TOO_SHORT',
    PASSWORD_WEAK: 'VALIDATION.PASSWORD_WEAK',
    IMAGES_NOT_BELONG_TO_PROJECT: 'VALIDATION.IMAGES_NOT_BELONG_TO_PROJECT',
  },
  NOT_FOUND: {
    USER_NOT_FOUND: 'NOT_FOUND.USER_NOT_FOUND',

    PROJECT_NOT_FOUND: 'NOT_FOUND.PROJECT_NOT_FOUND',

    CATEGORY_NOT_FOUND: 'NOT_FOUND.CATEGORY_NOT_FOUND',

    MAIN_IMAGE_NOT_FOUND: 'NOT_FOUND.MAIN_IMAGE_NOT_FOUND',

    PAGE_NOT_FOUND: 'NOT_FOUND.PAGE_NOT_FOUND',

    RESOURCE_NOT_FOUND: 'NOT_FOUND.RESOURCE_NOT_FOUND',

    TESTIMONIAL_NOT_FOUND: 'NOT_FOUND.TESTIMONIAL_NOT_FOUND',
  },
  CONFLICT: {
    EMAIL_ALREADY_EXISTS: 'CONFLICT.EMAIL_ALREADY_EXISTS',

    PROJECT_TITLE_EXISTS: 'CONFLICT.PROJECT_TITLE_EXISTS',
  },
  SERVER: {
    USER: {
      REGISTRATION_FAILED: 'SERVER.USER.REGISTRATION_FAILED',
      LOGIN_FAILED: 'SERVER.USER.LOGIN_FAILED',
      FETCH_USER_FAILED: 'SERVER.USER.FETCH_USER_FAILED',
      REFRESH_TOKEN_FAILED: 'SERVER.USER.REFRESH_TOKEN_FAILED',
    },

    CONTACT: {
      SUBMIT_FAILED: 'SERVER.CONTACT.SUBMIT_FAILED',
      FETCH_SUBMISSIONS_FAILED: 'SERVER.CONTACT.FETCH_SUBMISSIONS_FAILED',
      FETCH_SUBMISSION_BY_ID_FAILED:
        'SERVER.CONTACT.FETCH_SUBMISSION_BY_ID_FAILED',
      UPDATE_SUBMISSION_FAILED: 'SERVER.CONTACT.UPDATE_SUBMISSION_FAILED',
      DELETE_SUBMISSION_FAILED: 'SERVER.CONTACT.DELETE_SUBMISSION_FAILED',
    },

    PROJECT: {
      CREATE_FAILED: 'SERVER.PROJECT.CREATE_FAILED',
      UPDATE_FAILED: 'SERVER.PROJECT.UPDATE_FAILED',
      DELETE_FAILED: 'SERVER.PROJECT.DELETE_FAILED',
      FETCHS_FAILED: 'SERVER.PROJECT.FETCHS_FAILED',
      FETCH_FAVOURITES_FAILED: 'SERVER.PROJECT.FETCH_FAVOURITES_FAILED',
      FETCH_BY_ID_FAILED: 'SERVER.PROJECT.FETCH_BY_ID_FAILED',
    },

    TESTIMONIAL: {
      CREATE_FAILED: 'SERVER.TESTIMONIAL.CREATE_FAILED',
      UPDATE_FAILED: 'SERVER.TESTIMONIAL.UPDATE_FAILED',
      DELETE_FAILED: 'SERVER.TESTIMONIAL.DELETE_FAILED',
      FETCHS_FAILED: 'SERVER.TESTIMONIAL.FETCHS_FAILED',
      FETCH_BY_ID_FAILED: 'SERVER.TESTIMONIAL.FETCH_BY_ID_FAILED',
    },
  },
  NETWORK: {
    CONNECTION_ERROR: 'NETWORK.CONNECTION_ERROR',
    TIMEOUT: 'NETWORK.TIMEOUT',
    SERVER_ERROR: 'NETWORK.SERVER_ERROR',
    UNKNOWN_ERROR: 'NETWORK.UNKNOWN_ERROR',
  },
} as const;

// A helper to extract all string values from the nested object
export type DeepValue<T> = T extends object
  ? { [K in keyof T]: DeepValue<T[K]> }[keyof T]
  : T;

export type ErrorKey = DeepValue<typeof ERROR_KEYS>;

// הגדרת המבנה של המפה
export type ErrorMap<T extends string> = Record<ErrorKey, T>;

/**
 * פונקציה גנרית לשליפת הודעה
 */
export function formatErrorMessage<T extends string>(
  map: ErrorMap<T>,
  key: ErrorKey,
): T {
  return map[key] ?? `Unknown Error (${key})`;
}
