export const articleSchemas = {
  ArticleFaqItem: {
    type: 'object',
    properties: {
      question: { type: 'string', maxLength: 300 },
      answer: { type: 'string', maxLength: 2000 },
    },
    required: ['question', 'answer'],
  },
  ArticleResponse: {
    type: 'object',
    properties: {
      id: { type: 'string', format: 'cuid' },
      title: { type: 'string' },
      slug: { type: 'string', description: 'URL segment; Hebrew slugs are kept as-is' },
      excerpt: { type: 'string', description: 'Sanitised HTML' },
      body: { type: 'string', description: 'Sanitised HTML' },
      coverImage: { type: 'string', format: 'uri' },
      coverImageAlt: { type: 'string', nullable: true },
      coverImagePublicId: { type: 'string', nullable: true },
      category: { type: 'string', nullable: true },
      readingMinutes: { type: 'integer', minimum: 1 },
      faq: { type: 'array', items: { $ref: '#/components/schemas/ArticleFaqItem' } },
      seoTitle: { type: 'string', nullable: true },
      seoDescription: { type: 'string', nullable: true },
      published: { type: 'boolean' },
      publishedAt: { type: 'string', format: 'date-time', nullable: true },
      createdAt: { type: 'string', format: 'date-time' },
      updatedAt: { type: 'string', format: 'date-time' },
    },
    required: [
      'id',
      'title',
      'slug',
      'excerpt',
      'body',
      'coverImage',
      'readingMinutes',
      'faq',
      'published',
      'createdAt',
      'updatedAt',
    ],
  },
  ArticleSummaryResponse: {
    type: 'object',
    description: 'An article without its body or FAQ — what listings need.',
    properties: {
      id: { type: 'string', format: 'cuid' },
      title: { type: 'string' },
      slug: { type: 'string' },
      excerpt: { type: 'string' },
      coverImage: { type: 'string', format: 'uri' },
      coverImageAlt: { type: 'string', nullable: true },
      category: { type: 'string', nullable: true },
      readingMinutes: { type: 'integer' },
      published: { type: 'boolean' },
      publishedAt: { type: 'string', format: 'date-time', nullable: true },
    },
    required: ['id', 'title', 'slug', 'excerpt', 'coverImage', 'published'],
  },
  CreateArticleRequest: {
    type: 'object',
    properties: {
      title: { type: 'string', minLength: 2, maxLength: 200 },
      slug: { type: 'string', maxLength: 120, description: 'Derived from the title when omitted' },
      excerpt: { type: 'string', minLength: 10, maxLength: 600 },
      body: { type: 'string', maxLength: 60000 },
      coverImage: { type: 'string', format: 'uri' },
      coverImageAlt: { type: 'string', maxLength: 300 },
      category: { type: 'string' },
      readingMinutes: { type: 'integer', minimum: 1, maximum: 120 },
      faq: { type: 'array', maxItems: 20, items: { $ref: '#/components/schemas/ArticleFaqItem' } },
      seoTitle: { type: 'string', maxLength: 200 },
      seoDescription: { type: 'string', maxLength: 300 },
      published: { type: 'boolean', default: false },
    },
    required: ['title', 'excerpt', 'body', 'coverImage'],
  },
  UpdateArticleRequest: {
    type: 'object',
    description: 'Every field is optional; only what is sent is changed.',
    properties: {
      title: { type: 'string', minLength: 2, maxLength: 200 },
      slug: { type: 'string', maxLength: 120 },
      excerpt: { type: 'string', minLength: 10, maxLength: 600 },
      body: { type: 'string', maxLength: 60000 },
      coverImage: { type: 'string', format: 'uri' },
      coverImageAlt: { type: 'string', maxLength: 300 },
      category: { type: 'string' },
      faq: { type: 'array', maxItems: 20, items: { $ref: '#/components/schemas/ArticleFaqItem' } },
      seoTitle: { type: 'string', maxLength: 200 },
      seoDescription: { type: 'string', maxLength: 300 },
      published: { type: 'boolean' },
    },
  },
  ArticleImageUploadResponse: {
    type: 'object',
    properties: {
      url: { type: 'string', format: 'uri' },
      publicId: { type: 'string' },
    },
    required: ['url', 'publicId'],
  },
};
