export const calculatorSchemas = {
  CalculatorLeadResponse: {
    type: 'object',
    properties: {
      id: { type: 'string', format: 'cuid' },
      name: { type: 'string' },
      email: { type: 'string', format: 'email' },
      phoneNumber: { type: 'string' },
      builtAreaSqm: { type: 'integer' },
      constructionFinish: { type: 'string' },
      pool: { type: 'string' },
      outdoorAreaSqm: { type: 'integer' },
      outdoorFinish: { type: 'string' },
      kitchen: { type: 'string' },
      carpentry: { type: 'string' },
      furniture: { type: 'string' },
      equipment: { type: 'string' },
      priceDisplay: { type: 'string' },
      estimateMin: { type: 'integer' },
      estimateMax: { type: 'integer' },
      isRead: { type: 'boolean' },
      createdAt: { type: 'string', format: 'date-time' },
    },
  },
  SubmitCalculatorLeadRequest: {
    type: 'object',
    required: [
      'name',
      'email',
      'phoneNumber',
      'builtAreaSqm',
      'constructionFinish',
      'pool',
      'outdoorAreaSqm',
      'outdoorFinish',
      'kitchen',
      'carpentry',
      'furniture',
      'equipment',
      'estimate',
    ],
    properties: {
      name: { type: 'string' },
      email: { type: 'string', format: 'email' },
      phoneNumber: { type: 'string' },
      builtAreaSqm: { type: 'number' },
      constructionFinish: { type: 'string', enum: ['standard', 'invested', 'premium'] },
      pool: { type: 'string', enum: ['none', 'small', 'medium', 'large'] },
      outdoorAreaSqm: { type: 'number' },
      outdoorFinish: { type: 'string', enum: ['standard', 'invested', 'premium'] },
      kitchen: { type: 'string', enum: ['standard', 'invested', 'premium'] },
      carpentry: { type: 'string', enum: ['none', 'ready', 'custom'] },
      furniture: { type: 'string', enum: ['none', 'basic', 'full'] },
      equipment: { type: 'string', enum: ['none', 'basic', 'full'] },
      priceDisplay: { type: 'string', enum: ['before_vat'], description: 'Optional; defaults to before_vat' },
      estimate: { type: 'number' },
    },
  },
  CalculatorConfig: {
    type: 'object',
    properties: {
      builtAreaSqmRange: {
        type: 'object',
        properties: { min: { type: 'number' }, max: { type: 'number' } },
        description: 'Allowed built area range in sqm (e.g. 100–500)',
      },
      constructionBase: {
        type: 'object',
        properties: { min: { type: 'number' }, max: { type: 'number' } },
      },
      outdoorBase: {
        type: 'object',
        properties: { min: { type: 'number' }, max: { type: 'number' } },
      },
      finishMultipliers: { type: 'object' },
      poolAddons: { type: 'object' },
      kitchenAddons: { type: 'object' },
      carpentryAddons: { type: 'object' },
      furnitureAddons: { type: 'object' },
      equipmentAddons: { type: 'object' },
      vatMultiplier: { type: 'number' },
    },
  },
};
